Repository Rajput-xv/Health-Report-Analyzer, pull requests merged in 2025-08, with the labels that each got.

#18 Issue #8 Fixed(2)
  .gitignore
  client/src/components/AuthForm.jsx
  client/src/components/ForgotPassword.jsx
  client/src/components/ResetPassword.jsx
  client/src/utils/api.js
  package-lock.json
  package.json
  server/models/User.js
  server/routes/auth.js
Labels: enhancement, level 2, gssoc

#42 Added eye toggle to view/hide password
  client/src/components/AuthForm.jsx
Labels: enhancement, level 1, gssoc'25

#47 Improve password security and add firebase config
  client/src/components/AuthForm.jsx
  client/src/components/firebase.js
  client/vite.config.js
  server/config/database.js
  server/models/User.js
Labels: enhancement, level 2, gssoc'25

#62 Feat: Add 'Sign Up' Button to Landing Page Header
  client/src/App.jsx
  client/src/components/AuthForm.jsx
  client/src/components/LandingPage.jsx
  client/src/styles/landing.css
Labels: enhancement, level 1, gssoc'25
