Repository Rajput-xv/Health-Report-Analyzer, pull requests merged in 2025-09, with the labels that each got.

#69 add proper link to "sign in" in forgot-password
  client/src/components/ForgotPassword.jsx
Labels: enhancement, level 1, gssoc'25

#77 Add Favicon for Better Branding & User Experience #31
  client/index.html
  client/public/Health Report Analyzer Logo.png
Labels: enhancement, level 1, gssoc'25

#82 Implement Contact Us form using Forms API to send email
  client/src/App.jsx
  client/src/components/ContactUs.jsx
  client/src/styles/App.css
  client/src/styles/ContactUs.css
Labels: enhancement, level 3, gssoc'25

#103 Fix header alignment
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/styles/App.css
  server/package-lock.json
  server/package.json
Labels: enhancement, level 1, gssoc25

#108 accordion added in FAQ section
  client/src/components/FAQ.jsx
  client/src/styles/FAQ.css
Labels: enhancement, level 2, gssoc25

#109 Added Logout Confirmation Overlay
  client/src/components/LandingPage.jsx
  client/src/components/UserProfile.jsx
  client/src/styles/landing.css
Labels: enhancement, level 2, gssoc25

#125 Add global loading spinner with fade effect and context integration
  client/src/App.jsx
  client/src/components/FileUpload.jsx
  client/src/components/LoadingSpinner.jsx
  client/src/context/LoadingContext.jsx
  client/src/main.jsx
  client/src/styles/global.css
Labels: enhancement, level 2, gssoc25

#133 Make the logo text clickable and redirect to main landing page
  client/src/App.jsx
  client/src/components/Header.jsx
  client/src/components/LandingPage.jsx
Labels: enhancement, level 1, gssoc25

#140 Low text contrast in 'Secure Platform' box during Dark Mode and also FAQ section
  client/package-lock.json
  client/package.json
  client/postcss.config.cjs
  client/src/components/AuthForm.jsx
  client/src/styles/AuthForm.css
  client/src/styles/FAQ.css
Labels: enhancement, level 2, gssoc25

#164 AOS Animations added
  client/index.html
  client/src/components/FAQ.jsx
  client/src/components/LandingPage.jsx
  package-lock.json
  package.json
Labels: enhancement, level 2, gssoc25

#167 Data Visualization
  client/package-lock.json
  client/src/components/Dashboard.jsx
  client/src/components/DataVisualization.jsx
  client/src/components/LandingPage.jsx
  client/src/styles/dashboard.css
  client/src/styles/datavisualization.css
Labels: enhancement, level 3, gssoc25
